import { Scenario } from '@/types/game';

export const scenarios: Scenario[] = [
  {
    id: 1,
    title: '신입생 환영회 대참사',
    description: '신입생 환영회를 위해 예약한 펜션에서 갑자기 예약 취소 통보가 왔다! 환영회까지 3일밖에 안 남았는데...',
    weekRange: [1, 1],
    choices: [
      { id: '1a', text: '비싼 펜션으로 긴급 변경 (예산 투입)', effects: { satisfaction: 15, budget: -20, career: 0, academic: 0 } },
      { id: '1b', text: '학교 강당에서 간소하게 진행', effects: { satisfaction: -10, budget: 5, career: 0, academic: 5 } },
      { id: '1c', text: '환영회 취소하고 학과별 소모임으로 대체', effects: { satisfaction: -5, budget: 10, career: 0, academic: 10 } },
    ],
  },
  {
    id: 2,
    title: '급식 대란',
    description: '학교 식당 운영 업체가 갑자기 계약을 파기했다! 1,100명의 학생들이 당장 내일부터 먹을 곳이 없다.',
    weekRange: [2, 2],
    choices: [
      { id: '2a', text: '학생회 예산으로 임시 도시락 지원', effects: { satisfaction: 10, budget: -25, career: 0, academic: 0 } },
      { id: '2b', text: '진주시에 긴급 식품 지원 요청', effects: { satisfaction: 5, budget: 0, career: -15, academic: 0 } },
      { id: '2c', text: '학생들에게 자율 해결 안내 (근처 식당 목록 공유)', effects: { satisfaction: -15, budget: 0, career: 0, academic: -5 } },
    ],
  },
  {
    id: 3,
    title: '교육부 평가단 방문',
    description: '교육부 현장 평가단이 갑작스럽게 학교를 방문한다! 실습실이 엉망인데 하루 만에 정비해야 한다.',
    weekRange: [3, 3],
    choices: [
      { id: '3a', text: '수업을 임시 중단하고 전체 학생 동원 대청소', effects: { satisfaction: -10, budget: -5, career: 20, academic: -10 } },
      { id: '3b', text: '가장 깨끗한 실습실만 선별 안내', effects: { satisfaction: 0, budget: 0, career: 5, academic: 0 } },
      { id: '3c', text: '솔직하게 현 상황 설명하고 지원 요청', effects: { satisfaction: 5, budget: 0, career: 10, academic: 5 } },
    ],
  },
  {
    id: 4,
    title: '학과 간 실습실 전쟁',
    description: '전기과와 전자과가 공용 실습실 사용 시간을 두고 대립 중이다. 양쪽 다 자격증 시험이 코앞이라 양보할 수 없다고 한다.',
    weekRange: [4, 4],
    choices: [
      { id: '4a', text: '야간 개방 시간을 늘려 양쪽 배정 (예산 투입)', effects: { satisfaction: 10, budget: -15, career: 0, academic: 15 } },
      { id: '4b', text: '추첨으로 공정하게 결정', effects: { satisfaction: -5, budget: 0, career: 0, academic: 5 } },
      { id: '4c', text: '주말 실습실 개방으로 시간 분산', effects: { satisfaction: 0, budget: -5, career: 5, academic: 10 } },
    ],
  },
  {
    id: 5,
    title: '자격증 시험 시즌',
    description: '자격증 시험 시즌이 다가오자 학생들이 스터디 공간을 요구하고 있다. 하지만 학교에 빈 강의실이 부족하다.',
    weekRange: [5, 5],
    choices: [
      { id: '5a', text: '도서관 야간 개방 + 스터디 카페 제휴 (예산 투입)', effects: { satisfaction: 10, budget: -15, career: 0, academic: 20 } },
      { id: '5b', text: '기존 시설로 시간표 조정만 진행', effects: { satisfaction: -5, budget: 0, career: 0, academic: 5 } },
      { id: '5c', text: '지역 기업에 스터디 공간 지원 요청', effects: { satisfaction: 5, budget: 0, career: -10, academic: 15 } },
    ],
  },
  {
    id: 6,
    title: 'MT 예산 논란',
    description: '5개 학과 MT 예산을 배분해야 하는데, 총 예산이 요청액의 절반밖에 안 된다. 학과장들이 들고 일어났다!',
    weekRange: [6, 6],
    choices: [
      { id: '6a', text: '인원 비례로 공정 배분', effects: { satisfaction: -5, budget: 5, career: 0, academic: 0 } },
      { id: '6b', text: '학생회 비상금 풀어서 전액 지원', effects: { satisfaction: 15, budget: -20, career: 0, academic: 5 } },
      { id: '6c', text: '학과별 자체 모금 + 학생회 매칭 지원', effects: { satisfaction: 5, budget: -10, career: 0, academic: 10 } },
    ],
  },
  {
    id: 7,
    title: '기숙사 와이파이 전쟁',
    description: '기숙사 와이파이가 2주째 끊기고 있다. 학생들의 불만이 극에 달했고, 인터넷 없이 과제 제출도 못하는 상황이다.',
    weekRange: [7, 7],
    choices: [
      { id: '7a', text: '학생회 예산으로 임시 핫스팟 장비 대여', effects: { satisfaction: 10, budget: -15, career: 0, academic: 10 } },
      { id: '7b', text: '지역 통신사에 임시 인터넷 후원 요청', effects: { satisfaction: 5, budget: 0, career: -10, academic: 5 } },
      { id: '7c', text: '학교 행정실에 강력 항의', effects: { satisfaction: 5, budget: 0, career: 5, academic: 5 } },
    ],
  },
  {
    id: 8,
    title: '축제 기획의 늪',
    description: '대동제 예산이 작년 대비 30% 삭감됐다. 학생들은 화려한 축제를 기대하고 있고, 지역 기업들도 관심을 보이고 있다.',
    weekRange: [8, 8],
    choices: [
      { id: '8a', text: '지역 기업 협찬을 받아 대규모 축제 진행', effects: { satisfaction: 20, budget: 5, career: -10, academic: -10 } },
      { id: '8b', text: '소규모 알뜰 축제로 변경', effects: { satisfaction: -10, budget: 15, career: 0, academic: 5 } },
      { id: '8c', text: '학과별 부스 운영으로 자체 수익 창출', effects: { satisfaction: 5, budget: 10, career: 5, academic: 0 } },
    ],
  },
  {
    id: 9,
    title: '교수님의 분노',
    description: '전체 출석률이 60% 아래로 떨어졌다. 교수회의에서 학생회장에게 책임을 묻겠다는 이야기가 나왔다.',
    weekRange: [9, 9],
    choices: [
      { id: '9a', text: '출석 체크 캠페인 + 개근상 도입', effects: { satisfaction: -5, budget: -10, career: 5, academic: 20 } },
      { id: '9b', text: '교수님들과 간담회 개최 (절충안 모색)', effects: { satisfaction: 0, budget: -5, career: 5, academic: 10 } },
      { id: '9c', text: '학생들 편에서 수업 개선 요구', effects: { satisfaction: 15, budget: 0, career: -10, academic: -5 } },
    ],
  },
  {
    id: 10,
    title: '갑작스러운 감사',
    description: '학교 감사팀이 학생회 회계장부를 제출하라고 한다. 장부 정리가 안 되어 있어 문제가 될 수 있다!',
    weekRange: [10, 10],
    choices: [
      { id: '10a', text: '밤새 장부 정리 후 정직하게 제출', effects: { satisfaction: 0, budget: -5, career: 10, academic: 0 } },
      { id: '10b', text: '감사 연기 요청 (시간 벌기)', effects: { satisfaction: 0, budget: 0, career: -5, academic: 0 } },
      { id: '10c', text: '외부 회계사 긴급 투입', effects: { satisfaction: 5, budget: -15, career: 15, academic: 0 } },
    ],
  },
  {
    id: 11,
    title: '진주 홍수 경보',
    description: '진주에 폭우가 쏟아져 통학로가 침수됐다. 통학생 절반이 학교에 올 수 없는 상황이다.',
    weekRange: [11, 11],
    choices: [
      { id: '11a', text: '학생회 차량으로 긴급 셔틀 운행', effects: { satisfaction: 15, budget: -20, career: 0, academic: 5 } },
      { id: '11b', text: '온라인 수업 전환 요청', effects: { satisfaction: 5, budget: 0, career: 0, academic: -5 } },
      { id: '11c', text: '임시 휴강 건의', effects: { satisfaction: 10, budget: 0, career: -5, academic: -15 } },
    ],
  },
  {
    id: 12,
    title: '선배의 취업 SOS',
    description: '졸업을 앞둔 4학기 선배들이 취업 준비 지원을 요청했다. 이력서 첨삭, 면접 스터디 등을 학생회에서 운영해달라고 한다.',
    weekRange: [12, 12],
    choices: [
      { id: '12a', text: '지역 기업 현직자 멘토링 프로그램 운영', effects: { satisfaction: 10, budget: 0, career: 15, academic: 15 } },
      { id: '12b', text: '학생회 자체 취업 스터디 운영', effects: { satisfaction: 5, budget: -10, career: 0, academic: 10 } },
      { id: '12c', text: '진주 지역 중소기업 채용 박람회 개최', effects: { satisfaction: 0, budget: -5, career: 5, academic: 5 } },
    ],
  },
  {
    id: 13,
    title: '동아리 예산 쟁탈전',
    description: '15개 동아리가 예산 신청을 했는데, 배정 가능한 금액은 신청액의 1/3이다. 인기 동아리와 소규모 동아리 간 갈등이 심화됐다.',
    weekRange: [13, 13],
    choices: [
      { id: '13a', text: '활동 실적 기반 차등 배분', effects: { satisfaction: -5, budget: 5, career: 0, academic: 5 } },
      { id: '13b', text: '균등 배분으로 공평하게', effects: { satisfaction: 0, budget: 0, career: 0, academic: 0 } },
      { id: '13c', text: '취업·진로 연계 동아리에 우선 배분', effects: { satisfaction: -10, budget: 10, career: 10, academic: 5 } },
    ],
  },
  {
    id: 14,
    title: '지역 기업 인턴십 배분',
    description: '지역 기업 연합에서 인턴 5자리를 배정해줬는데, 지원자가 30명이다. 선발 기준을 학생회에서 정해달라고 한다.',
    weekRange: [14, 14],
    choices: [
      { id: '14a', text: '성적순으로 공정하게 선발', effects: { satisfaction: -10, budget: 0, career: 10, academic: 15 } },
      { id: '14b', text: '포트폴리오 + 면접 종합 평가', effects: { satisfaction: 5, budget: -5, career: 5, academic: 10 } },
      { id: '14c', text: '기업에 추가 인턴 자리 요청', effects: { satisfaction: 10, budget: 0, career: 10, academic: 5 } },
    ],
  },
  {
    id: 15,
    title: '학교 SNS 논란',
    description: '학생회 인스타에 올린 게시물이 논란이 되었다. 일부 학과를 비하하는 내용으로 해석될 수 있다는 지적이 쏟아지고 있다.',
    weekRange: [15, 15],
    choices: [
      { id: '15a', text: '즉시 삭제하고 공식 사과문 게시', effects: { satisfaction: 5, budget: 0, career: 0, academic: 0 } },
      { id: '15b', text: '해명 글 게시 (의도 설명)', effects: { satisfaction: -5, budget: 0, career: 0, academic: 0 } },
      { id: '15c', text: '무대응 (시간이 해결해줄 것)', effects: { satisfaction: -15, budget: 0, career: -5, academic: 0 } },
    ],
  },
  {
    id: 16,
    title: '자유전공학과의 반란',
    description: '2026년 신설된 자유전공학과 학생들이 기존 학과와 동등한 시설 사용권을 요구하고 있다. 기존 학과 학생들은 반발하고 있다.',
    weekRange: [16, 16],
    choices: [
      { id: '16a', text: '자유전공학과에 별도 실습 시간 배정', effects: { satisfaction: 0, budget: -10, career: 5, academic: 10 } },
      { id: '16b', text: '기존 학과 우선 원칙 유지', effects: { satisfaction: -5, budget: 0, career: 0, academic: -5 } },
      { id: '16c', text: '전체 학생 투표로 결정', effects: { satisfaction: 5, budget: -5, career: 0, academic: 0 } },
    ],
  },
  {
    id: 17,
    title: '에어컨 전쟁',
    description: '한여름인데 강의실 에어컨 절반이 고장났다. 학교는 예산 부족으로 수리가 어렵다고 한다. 학생들의 불만이 폭발 직전이다.',
    weekRange: [17, 17],
    choices: [
      { id: '17a', text: '학생회 예산으로 긴급 수리', effects: { satisfaction: 15, budget: -25, career: 0, academic: 10 } },
      { id: '17b', text: '진주시에 냉방 시설 지원 요청', effects: { satisfaction: 10, budget: 0, career: -15, academic: 5 } },
      { id: '17c', text: '선풍기 + 아이스크림 이벤트로 버티기', effects: { satisfaction: -5, budget: -10, career: 0, academic: -5 } },
    ],
  },
  {
    id: 18,
    title: '해커톤 대회 개최',
    description: '지역 기업 연합에서 교내 해커톤 대회를 후원하겠다고 제안했다. 좋은 기회지만 준비에 많은 시간과 인력이 필요하다.',
    weekRange: [18, 18],
    choices: [
      { id: '18a', text: '대규모로 개최 (전 학과 참여)', effects: { satisfaction: 10, budget: -15, career: 20, academic: 15 } },
      { id: '18b', text: '소규모 파일럿으로 시작', effects: { satisfaction: 0, budget: -5, career: 10, academic: 10 } },
      { id: '18c', text: '시기상조라며 정중히 거절', effects: { satisfaction: 0, budget: 0, career: -20, academic: 0 } },
    ],
  },
  {
    id: 19,
    title: '졸업 작품 대란',
    description: '졸업 작품 전시회가 한 달 앞으로 다가왔는데, 절반의 팀이 재료비가 부족하다고 SOS를 보내왔다.',
    weekRange: [19, 19],
    choices: [
      { id: '19a', text: '학생회 예산에서 재료비 지원', effects: { satisfaction: 10, budget: -20, career: 0, academic: 15 } },
      { id: '19b', text: '지역 기업에 졸업 작품 후원 요청', effects: { satisfaction: 5, budget: 0, career: 10, academic: 10 } },
      { id: '19c', text: '자체 해결하도록 안내', effects: { satisfaction: -15, budget: 5, career: 0, academic: -10 } },
    ],
  },
  {
    id: 20,
    title: '취업률 위기',
    description: '대기업들이 올해 채용 규모를 40% 축소한다고 발표했다. 취업을 준비하던 학생들이 패닉에 빠졌다.',
    weekRange: [20, 20],
    choices: [
      { id: '20a', text: '다른 대기업 취업 설명회 유치', effects: { satisfaction: 10, budget: -15, career: -5, academic: 10 } },
      { id: '20b', text: '기업 인사팀에 특별 채용 요청', effects: { satisfaction: 5, budget: 0, career: 10, academic: 5 } },
      { id: '20c', text: '창업 지원 프로그램으로 방향 전환', effects: { satisfaction: 0, budget: -10, career: 5, academic: 15 } },
    ],
  },
  {
    id: 21,
    title: '후배 학생회장 선거',
    description: '차기 학생회장 선거인데 후보가 아무도 없다! 학생들의 무관심이 심각한 상황이다.',
    weekRange: [21, 21],
    choices: [
      { id: '21a', text: '학생회장 혜택 패키지 만들어 홍보', effects: { satisfaction: 5, budget: -10, career: 0, academic: -5 } },
      { id: '21b', text: '직접 후배를 설득해서 출마시킴', effects: { satisfaction: 10, budget: 0, career: 0, academic: 0 } },
      { id: '21c', text: '선거 없이 학생회 해체 위기 방치', effects: { satisfaction: -20, budget: 0, career: -10, academic: -10 } },
    ],
  },
  {
    id: 22,
    title: '캡스톤 디자인 심사위원',
    description: '캡스톤 디자인 발표회에 지역 기업 인사를 심사위원으로 초청했는데, 학생들의 프로젝트 완성도가 걱정된다.',
    weekRange: [22, 22],
    choices: [
      { id: '22a', text: '사전 리허설 + 멘토링 집중 지원', effects: { satisfaction: 5, budget: -10, career: 15, academic: 15 } },
      { id: '22b', text: '완성도 높은 팀만 선별 발표', effects: { satisfaction: -10, budget: 0, career: 10, academic: 5 } },
      { id: '22c', text: '기업 심사위원 초청 취소', effects: { satisfaction: 0, budget: 0, career: -15, academic: 0 } },
    ],
  },
  {
    id: 23,
    title: '학교 근처 편의점 폐업',
    description: '학교 유일의 편의점이 폐업했다. 기숙사생들은 간식과 생필품을 구하기 어려워졌다.',
    weekRange: [23, 23],
    choices: [
      { id: '23a', text: '학생회 매점 임시 운영', effects: { satisfaction: 15, budget: -15, career: 0, academic: 0 } },
      { id: '23b', text: '편의점 유치 활동 (임대료 협상)', effects: { satisfaction: 5, budget: -5, career: 0, academic: 0 } },
      { id: '23c', text: '온라인 공동구매 플랫폼 구축', effects: { satisfaction: 10, budget: -10, career: 0, academic: 5 } },
    ],
  },
  {
    id: 24,
    title: '4년제 승격 논란',
    description: '학교가 4년제 승격을 추진한다는 소문이 돌고 있다. 학생들 사이에서 찬반 의견이 팽팽하게 갈리고 있다.',
    weekRange: [24, 24],
    choices: [
      { id: '24a', text: '학생 설문조사 실시 후 공식 입장 발표', effects: { satisfaction: 10, budget: -5, career: 5, academic: 5 } },
      { id: '24b', text: '4년제 승격 적극 찬성 입장 표명', effects: { satisfaction: -10, budget: 0, career: 15, academic: 10 } },
      { id: '24c', text: '중립 유지 (어느 쪽도 지지하지 않음)', effects: { satisfaction: -5, budget: 0, career: 0, academic: 0 } },
    ],
  },
  {
    id: 25,
    title: '졸업식 최후의 결전',
    description: '임기 마지막 주, 졸업식을 성공적으로 마무리해야 한다. 예산도 빠듯하고 지역 내빈이 축사를 하겠다고 했다.',
    weekRange: [25, 25],
    choices: [
      { id: '25a', text: '호화 졸업식 (외부 장소 대여 + 풀 세팅)', effects: { satisfaction: 20, budget: -25, career: 10, academic: 5 } },
      { id: '25b', text: '감성 졸업식 (강당 + 영상 + 학생 공연)', effects: { satisfaction: 15, budget: -5, career: 5, academic: 10 } },
      { id: '25c', text: '간소한 졸업식 (절약 모드)', effects: { satisfaction: -5, budget: 10, career: -5, academic: 0 } },
    ],
  },
  {
    id: 26,
    title: '봄 체육대회 논쟁',
    description: '전통적인 체육대회를 하자는 측과 e스포츠 대회를 하자는 측이 대립하고 있다.',
    weekRange: [26, 26],
    choices: [
      { id: '26a', text: '전통 체육대회 개최 (축구, 농구, 달리기)', effects: { satisfaction: -5, budget: -10, career: 0, academic: 0 } },
      { id: '26b', text: 'e스포츠 대회로 변경 (LOL, 배그)', effects: { satisfaction: 10, budget: -15, career: 5, academic: -5 } },
      { id: '26c', text: '양쪽 다 진행 (예산 부담)', effects: { satisfaction: 15, budget: -25, career: 0, academic: -10 } },
    ],
  },
  {
    id: 27,
    title: '실습 장비 고장',
    description: '외부 후원으로 들어온 고가의 실습 장비가 학생 부주의로 고장났다. 어떻게 처리할까?',
    weekRange: [27, 27],
    choices: [
      { id: '27a', text: '사실대로 보고하고 사과', effects: { satisfaction: -5, budget: 0, career: -15, academic: 5 } },
      { id: '27b', text: '학생회 예산으로 조용히 수리', effects: { satisfaction: 5, budget: -20, career: 0, academic: 0 } },
      { id: '27c', text: '자연 고장으로 위장해 A/S 요청', effects: { satisfaction: 10, budget: 0, career: -5, academic: 0 } },
    ],
  },
  {
    id: 28,
    title: '기숙사 소음 문제',
    description: '심야 시간대 기숙사 소음 민원이 폭증하고 있다. 학생들 간 갈등이 심각하다.',
    weekRange: [28, 28],
    choices: [
      { id: '28a', text: '야간 통금 시간 강화 (벌점제)', effects: { satisfaction: -10, budget: 0, career: 0, academic: 10 } },
      { id: '28b', text: '방음 시설 개선 요청', effects: { satisfaction: 5, budget: -15, career: 0, academic: 0 } },
      { id: '28c', text: '층별 자치규약 제정 유도', effects: { satisfaction: 0, budget: 0, career: 0, academic: 5 } },
    ],
  },
  {
    id: 29,
    title: '중간고사 부정행위',
    description: '대규모 중간고사 부정행위가 적발됐다. 학생들이 학생회에 탄원서를 제출했다.',
    weekRange: [29, 29],
    choices: [
      { id: '29a', text: '학생 편에서 선처 탄원', effects: { satisfaction: 15, budget: 0, career: -10, academic: -20 } },
      { id: '29b', text: '중립 유지', effects: { satisfaction: -5, budget: 0, career: 0, academic: 0 } },
      { id: '29c', text: '재발 방지 캠페인 진행', effects: { satisfaction: 0, budget: -5, career: 5, academic: 15 } },
    ],
  },
  {
    id: 30,
    title: '진주시 장학재단 장학금',
    description: '진주시 장학재단에서 1억 원 장학금을 지원한다. 배분 기준을 학생회에서 정해달라고 한다.',
    weekRange: [30, 30],
    choices: [
      { id: '30a', text: '성적 우수자 위주', effects: { satisfaction: -10, budget: 0, career: 10, academic: 20 } },
      { id: '30b', text: '저소득층 우선 지원', effects: { satisfaction: 15, budget: 0, career: 5, academic: 0 } },
      { id: '30c', text: '성적+가정형편 종합 평가', effects: { satisfaction: 5, budget: -5, career: 10, academic: 10 } },
    ],
  },
  {
    id: 31,
    title: '여름 냉방비 폭탄',
    description: '폭염으로 냉방비가 예상의 3배가 나왔다. 학생회 예산으로 일부 부담해야 한다.',
    weekRange: [31, 31],
    choices: [
      { id: '31a', text: '학생회 예산으로 전액 부담', effects: { satisfaction: 15, budget: -30, career: 0, academic: 0 } },
      { id: '31b', text: '학교 측에 비용 분담 요청', effects: { satisfaction: 5, budget: -10, career: -5, academic: 0 } },
      { id: '31c', text: '에어컨 가동 시간 축소', effects: { satisfaction: -15, budget: 0, career: 0, academic: -10 } },
    ],
  },
  {
    id: 32,
    title: '학과 통폐합 소문',
    description: '일부 학과가 통폐합된다는 소문이 돌고 있다. 해당 학과 학생들이 패닉 상태다.',
    weekRange: [32, 32],
    choices: [
      { id: '32a', text: '학교 측에 공식 입장 요구', effects: { satisfaction: 10, budget: 0, career: 5, academic: 5 } },
      { id: '32b', text: '학생 서명운동 진행', effects: { satisfaction: 15, budget: -5, career: -10, academic: 0 } },
      { id: '32c', text: '소문 확산 방지 (무대응)', effects: { satisfaction: -15, budget: 0, career: 0, academic: -10 } },
    ],
  },
  {
    id: 33,
    title: '진로 박람회 유치',
    description: '대규모 진로 박람회를 유치할 기회가 생겼다. 하지만 준비 기간이 2주밖에 안 된다.',
    weekRange: [33, 33],
    choices: [
      { id: '33a', text: '올인해서 대규모 개최', effects: { satisfaction: 20, budget: -25, career: 10, academic: 15 } },
      { id: '33b', text: '소규모로 축소 개최', effects: { satisfaction: 5, budget: -10, career: 5, academic: 10 } },
      { id: '33c', text: '시기상조라며 다음 학기로 연기', effects: { satisfaction: -5, budget: 0, career: 0, academic: 0 } },
    ],
  },
  {
    id: 34,
    title: '도서관 좌석 부족',
    description: '기말고사 시즌인데 도서관 좌석이 턱없이 부족하다. 밤샘 자리 선점 문제도 심각하다.',
    weekRange: [34, 34],
    choices: [
      { id: '34a', text: '24시간 스터디 카페 임대', effects: { satisfaction: 15, budget: -20, career: 0, academic: 15 } },
      { id: '34b', text: '빈 강의실 야간 개방', effects: { satisfaction: 5, budget: -5, career: 0, academic: 10 } },
      { id: '34c', text: '좌석 예약 시스템 도입 건의', effects: { satisfaction: 0, budget: -10, career: 0, academic: 5 } },
    ],
  },
  {
    id: 35,
    title: '학생회비 인상 압박',
    description: '학교 측이 학생회비를 20% 인상하라고 압박하고 있다. 학생들의 반발이 예상된다.',
    weekRange: [35, 35],
    choices: [
      { id: '35a', text: '학생 투표로 결정', effects: { satisfaction: 5, budget: 0, career: 0, academic: 0 } },
      { id: '35b', text: '인상 거부하고 학교와 대립', effects: { satisfaction: 10, budget: 0, career: -15, academic: 0 } },
      { id: '35c', text: '10%만 인상하는 절충안', effects: { satisfaction: -5, budget: 5, career: 5, academic: 0 } },
    ],
  },
  {
    id: 36,
    title: '교내 흡연 문제',
    description: '금연 구역에서 흡연하는 학생들 때문에 민원이 빗발치고 있다.',
    weekRange: [36, 36],
    choices: [
      { id: '36a', text: '흡연부스 설치 요청', effects: { satisfaction: 5, budget: -15, career: 0, academic: 0 } },
      { id: '36b', text: '금연 캠페인 + 단속 강화', effects: { satisfaction: -10, budget: -5, career: 5, academic: 5 } },
      { id: '36c', text: '전면 금연 캠퍼스 추진', effects: { satisfaction: -15, budget: 0, career: 10, academic: 10 } },
    ],
  },
  {
    id: 37,
    title: '교수 평가 시스템 논란',
    description: '교수 평가 결과를 공개하자는 요구가 나오고 있다. 교수회는 강력 반발 중이다.',
    weekRange: [37, 37],
    choices: [
      { id: '37a', text: '평가 결과 전면 공개 추진', effects: { satisfaction: 20, budget: 0, career: -15, academic: -10 } },
      { id: '37b', text: '익명 요약본만 공개', effects: { satisfaction: 5, budget: 0, career: -5, academic: 0 } },
      { id: '37c', text: '현행 유지 (비공개)', effects: { satisfaction: -15, budget: 0, career: 10, academic: 0 } },
    ],
  },
  {
    id: 38,
    title: '학생 창업 지원',
    description: '학생 창업팀이 학생회 투자를 요청했다. 성공하면 큰 수익이지만 실패 위험도 있다.',
    weekRange: [38, 38],
    choices: [
      { id: '38a', text: '학생회 예산으로 투자', effects: { satisfaction: 10, budget: -20, career: 5, academic: 10 } },
      { id: '38b', text: '지역 창업 지원 기관에 연결', effects: { satisfaction: 5, budget: 0, career: 10, academic: 15 } },
      { id: '38c', text: '투자 거절', effects: { satisfaction: -10, budget: 5, career: 0, academic: 0 } },
    ],
  },
  {
    id: 39,
    title: '해외 교환학생 불공정',
    description: '해외 교환학생 선발 과정이 불공정하다는 의혹이 제기됐다.',
    weekRange: [39, 39],
    choices: [
      { id: '39a', text: '선발 과정 재조사 요구', effects: { satisfaction: 10, budget: 0, career: -10, academic: 5 } },
      { id: '39b', text: '투명한 선발 기준 마련 건의', effects: { satisfaction: 5, budget: -5, career: 0, academic: 10 } },
      { id: '39c', text: '학교 입장 존중 (무대응)', effects: { satisfaction: -15, budget: 0, career: 10, academic: 0 } },
    ],
  },
  {
    id: 40,
    title: '가을 축제 vs 학술제',
    description: '가을 행사를 축제로 할지 학술제로 할지 의견이 갈린다.',
    weekRange: [40, 40],
    choices: [
      { id: '40a', text: '대규모 축제 개최', effects: { satisfaction: 15, budget: -25, career: -5, academic: -10 } },
      { id: '40b', text: '학술제 + 소규모 공연', effects: { satisfaction: 0, budget: -10, career: 10, academic: 20 } },
      { id: '40c', text: '양쪽 절충 (미니 축제+전시)', effects: { satisfaction: 10, budget: -20, career: 5, academic: 10 } },
    ],
  },
  {
    id: 41,
    title: '겨울 난방 갈등',
    description: '강의실 난방 온도를 두고 학생들 간 갈등이 발생하고 있다.',
    weekRange: [41, 41],
    choices: [
      { id: '41a', text: '난방 온도 상향 조정 요청', effects: { satisfaction: 10, budget: 0, career: 0, academic: 5 } },
      { id: '41b', text: '개인 난방 용품 지원', effects: { satisfaction: 5, budget: -15, career: 0, academic: 0 } },
      { id: '41c', text: '현행 온도 유지', effects: { satisfaction: -10, budget: 5, career: 0, academic: 0 } },
    ],
  },
  {
    id: 42,
    title: '교육부 특별 지원금',
    description: '교육부에서 학생 복지 개선을 위해 특별 지원금 1억 원을 배정했다. 사용처를 제안해야 한다.',
    weekRange: [42, 42],
    choices: [
      { id: '42a', text: '기숙사 시설 개선', effects: { satisfaction: 15, budget: 10, career: 10, academic: 0 } },
      { id: '42b', text: '실습 장비 추가 구매', effects: { satisfaction: 5, budget: 10, career: 15, academic: 20 } },
      { id: '42c', text: '학생 휴게 공간 조성', effects: { satisfaction: 20, budget: 10, career: 5, academic: -5 } },
    ],
  },
  {
    id: 43,
    title: '학점 인플레이션',
    description: '일부 교수의 학점 인플레이션 문제가 불거졌다. 학점 불이익을 받은 학생들이 항의하고 있다.',
    weekRange: [43, 43],
    choices: [
      { id: '43a', text: '학점 조정 요구', effects: { satisfaction: 15, budget: 0, career: -15, academic: -10 } },
      { id: '43b', text: '상대평가 기준 강화 건의', effects: { satisfaction: -5, budget: 0, career: 5, academic: 15 } },
      { id: '43c', text: '중립 유지', effects: { satisfaction: -10, budget: 0, career: 0, academic: 0 } },
    ],
  },
  {
    id: 44,
    title: '연말 송년회',
    description: '학생회 송년회 예산을 두고 의견이 갈린다. 화려하게 vs 검소하게.',
    weekRange: [44, 44],
    choices: [
      { id: '44a', text: '호텔 뷔페 송년회', effects: { satisfaction: 15, budget: -25, career: 0, academic: -5 } },
      { id: '44b', text: '교내 소규모 파티', effects: { satisfaction: 5, budget: -10, career: 0, academic: 0 } },
      { id: '44c', text: '송년회 취소하고 예산 이월', effects: { satisfaction: -10, budget: 10, career: 5, academic: 0 } },
    ],
  },
  {
    id: 45,
    title: '신입생 모집 홍보',
    description: '내년 신입생 모집을 위한 홍보에 학생회가 참여해달라는 요청이 왔다.',
    weekRange: [45, 45],
    choices: [
      { id: '45a', text: '대규모 홍보 캠페인 진행', effects: { satisfaction: 0, budget: -20, career: 15, academic: 5 } },
      { id: '45b', text: 'SNS 중심 홍보', effects: { satisfaction: 5, budget: -10, career: 10, academic: 5 } },
      { id: '45c', text: '최소한의 협조만', effects: { satisfaction: 0, budget: 0, career: -5, academic: 0 } },
    ],
  },
  {
    id: 46,
    title: '학생회 업무 인수인계',
    description: '차기 학생회에 인수인계를 시작해야 한다. 어느 정도까지 관여할지 고민이다.',
    weekRange: [46, 46],
    choices: [
      { id: '46a', text: '세밀한 인수인계 + 2주 공동 운영', effects: { satisfaction: 10, budget: -5, career: 5, academic: 0 } },
      { id: '46b', text: '문서 위주 간단 인수인계', effects: { satisfaction: 0, budget: 0, career: 0, academic: 0 } },
      { id: '46c', text: '전임자 경험 공유 세션 개최', effects: { satisfaction: 5, budget: -10, career: 5, academic: 5 } },
    ],
  },
  {
    id: 47,
    title: '예산 결산 보고',
    description: '1년 예산 결산 보고서를 작성해야 한다. 일부 항목이 불투명하다.',
    weekRange: [47, 47],
    choices: [
      { id: '47a', text: '투명하게 전부 공개', effects: { satisfaction: 15, budget: 0, career: 10, academic: 0 } },
      { id: '47b', text: '요약본만 공개', effects: { satisfaction: 0, budget: 0, career: 0, academic: 0 } },
      { id: '47c', text: '외부 회계 감사 받기', effects: { satisfaction: 10, budget: -15, career: 15, academic: 0 } },
    ],
  },
  {
    id: 48,
    title: '학생 민원 처리',
    description: '미처리된 학생 민원이 50건이나 쌓여있다. 마지막까지 책임질 것인가?',
    weekRange: [48, 48],
    choices: [
      { id: '48a', text: '야근해서라도 전부 처리', effects: { satisfaction: 20, budget: 0, career: 5, academic: -5 } },
      { id: '48b', text: '긴급 민원만 처리하고 인계', effects: { satisfaction: 5, budget: 0, career: 0, academic: 0 } },
      { id: '48c', text: '차기 학생회에 전부 인계', effects: { satisfaction: -15, budget: 0, career: -10, academic: 0 } },
    ],
  },
  {
    id: 49,
    title: '지역 후원기관 감사 행사',
    description: '1년간 학교를 지원해준 지역 후원기관에 감사 인사를 전해야 한다. 어떤 방식이 좋을까?',
    weekRange: [49, 49],
    choices: [
      { id: '49a', text: '감사패 증정식 + 기념 영상', effects: { satisfaction: 5, budget: -15, career: 20, academic: 0 } },
      { id: '49b', text: '학생 대표단 직접 방문', effects: { satisfaction: 10, budget: -10, career: 15, academic: 5 } },
      { id: '49c', text: '공식 감사 서한 발송', effects: { satisfaction: 0, budget: 0, career: 5, academic: 0 } },
    ],
  },
  {
    id: 50,
    title: '학생회 평가',
    description: '학생들에게 학생회 활동 평가를 받는다. 어떤 방식으로 받을까?',
    weekRange: [50, 50],
    choices: [
      { id: '50a', text: '익명 설문조사 + 공개 간담회', effects: { satisfaction: 15, budget: -5, career: 0, academic: 0 } },
      { id: '50b', text: '온라인 설문만 진행', effects: { satisfaction: 5, budget: 0, career: 0, academic: 0 } },
      { id: '50c', text: '평가 생략 (부담스러움)', effects: { satisfaction: -15, budget: 0, career: -10, academic: 0 } },
    ],
  },
  {
    id: 51,
    title: '마지막 전체 학생 총회',
    description: '임기 마지막 전체 학생 총회를 연다. 어떤 메시지를 남길까?',
    weekRange: [51, 51],
    choices: [
      { id: '51a', text: '성과 중심 보고 + 감사 인사', effects: { satisfaction: 10, budget: 0, career: 5, academic: 0 } },
      { id: '51b', text: '솔직한 반성 + 미래 제언', effects: { satisfaction: 15, budget: 0, career: 0, academic: 10 } },
      { id: '51c', text: '간단한 인사만', effects: { satisfaction: -5, budget: 0, career: 0, academic: 0 } },
    ],
  },
  {
    id: 52,
    title: '학생회장 임기 종료',
    description: '드디어 52주간의 긴 여정이 끝났다. 마지막으로 무엇을 할 것인가?',
    weekRange: [52, 52],
    choices: [
      { id: '52a', text: '차기 회장에게 격려 메시지', effects: { satisfaction: 10, budget: 0, career: 5, academic: 5 } },
      { id: '52b', text: '전체 학생에게 감사 인사', effects: { satisfaction: 15, budget: 0, career: 0, academic: 0 } },
      { id: '52c', text: '조용히 물러나기', effects: { satisfaction: 5, budget: 5, career: 0, academic: 0 } },
    ],
  },
];
